### PR TITLE
Add ability to include "media" and other CSS text

### PR DESCRIPTION
**Pull request by laurencei**
I've added a couple of small lines of code, which allows for "media" and other CSS functions with the Asset helper. This is backwards compatible

<?php Assets::css(array('bootstrap.less', 'init.css', 'style.css')); ?>

can now also be

<?php Assets::css(array('bootstrap.less', 'init.css', 'style.css'), 'media="print"'); ?>

and

<?php Assets::css_group('global', array('style.css')); ?>

can now also be

<?php Assets::css_group('global', array('style.css'), 'media="print"'); ?>

This is important, because new CSS styles, like bootstrap, use alot of media queries - like "only all and (min-width: 768px)" etc - these can now be included if required without hacking the assets library

### CODE REVIEW

**Comment by laurencei** [comment]
sorry - I dont know why the pull request is showing the whole file as different.

Only changes are lines 29, 71, 103, 813 and 814

**Comment by laurencei** [comment]
FYI - currently version 1.5 is not actually minfying JS files - because the wrong variable is used on line 451 in version 1.5

**Comment by bstrahija** [comment]
I've been actually working on this so there's no need for the pull request since I'll implement my own version. Should be done in a day or 2.

**Comment by laurencei** [comment]
Ok - but there is still the bug I fixed on line 451 in my pull request - currently version 1.5 does not minify JS files, even when set to true. I've fixed this.

**Comment by bstrahija** [comment]
I know about that one also, just haven't got around to it. All of this will be in the next version.

**Comment by laurencei** [comment]
Ok cool - thanks. Keep up the great work :)

**Pull request closed without merging**
